# Generated by Django 2.2.7 on 2019-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=32, verbose_name='Время замера')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=16)),
                ('lat_direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=2)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=16)),
                ('long_direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=2)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=16)),
                ('speed', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
        ),
    ]
